### PR TITLE
Distinguish cpu and gpu TF wheels

### LINKED ISSUE #13: HotFix, Not the best solution as cuda version can change!
https://github.com/thoth-station/httpd-aicoe-container/blob/645392b81fb55c75b62757eaa32ca8d0a4a62706/2.4/s2i/bin/assemble#L38-L43

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in 645392b81fb55c75b62757eaa32ca8d0a4a62706 when #12 was merged. cc @harshad16.

### PR DESCRIPTION
**Pull request by harshad16**
Distinguish cpu and gpu TF wheels
Fixes: #13  #9 
Index pattern:
```<host-url>/index/os/<os>/<os_version>/<tensorflow-cpu or tensorflow-gpu>/simple/tensorflow```
```<host-url>/index/manylinux/<tensorflow-cpu or tensorflow-gpu>/simple/tensorflow```

Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Comment by harshad16** [comment]
```.
├── manylinux2010
│   ├── tensorflow-cpu
│   │   └── simple
│   │       ├── tensorflow
│   │       │   ├── tensorflow-1.12.3-cp27-cp27mu-linux_x86_64.whl
│   │       │   ├── tensorflow-1.12.3-cp36-cp36m-linux_x86_64.whl
│   │       │   ├── tensorflow-1.13.2-cp36-cp36m-linux_x86_64.whl
│   │       │   ├── tensorflow-1.14.1-cp27-cp27mu-linux_x86_64.whl
│   │       │   ├── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
│   │       │   ├── tensorflow-1.15.0rc2-cp36-cp36m-linux_x86_64.whl
│   │       │   ├── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
│   │       │   ├── tensorflow-2.0.0-cp37-cp37m-linux_x86_64.whl
│   │       │   ├── tensorflow-2.0.0rc0-cp27-cp27mu-linux_x86_64.whl
│   │       │   └── tensorflow-2.0.0rc0-cp36-cp36m-linux_x86_64.whl
│   │       └── tensorflow-serving-api
│   │           ├── tensorflow_serving_api-1.12.3-py2.py3-none-any.whl
│   │           ├── tensorflow_serving_api-1.13.0-py2.py3-none-any.whl
│   │           └── tensorflow_serving_api-1.14.0-py2.py3-none-any.whl
│   └── tensorflow-gpu
│       └── simple
│           └── tensorflow
│               ├── tensorflow-2.0.0rc2-cp36-cp36m-linux_x86_64.whl
│               ├── tensorflow-gpu-2.0.0-cp36-cp36m-linux_x86_64.whl
│               └── tensorflow-gpu-2.0.0-cp37-cp37m-linux_x86_64.whl
└── os
    ├── centos
    │   └── 7
    │       ├── tensorflow-cpu
    │       │   └── simple
    │       │       ├── tensorflow
    │       │       │   ├── tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl
    │       │       │   ├── tensorflow-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl
    │       │       │   ├── tensorflow-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl
    │       │       │   ├── tensorflow-1.12.0-cp36-cp36m-manylinux1_x86_64.whl
    │       │       │   ├── tensorflow-1.12.2-cp36-cp36m-manylinux1_x86_64.whl
    │       │       │   ├── tensorflow-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl
    │       │       │   ├── tensorflow-1.13.1-cp36-cp36m-manylinux1_x86_64.whl
    │       │       │   ├── tensorflow-1.9.0-cp27-cp27mu-manylinux1_x86_64.whl
    │       │       │   └── tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl
    │       │       └── tensorflow-serving-api
    │       │           ├── tensorflow_serving_api-1.12.0-py2.py3-none-any.whl
    │       │           ├── tensorflow_serving_api-1.13.0-py2.py3-none-any.whl
    │       │           └── tensorflow_serving_api-1.14.0-py2.py3-none-any.whl
    │       └── tensorflow-gpu
    │           └── simple
    │               └── tensorflow
    │                   └── tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl
    ├── fedora
    │   ├── 26
    │   │   └── tensorflow-cpu
    │   │       └── simple
    │   │           └── tensorflow
    │   │               └── tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl
    │   ├── 27
    │   │   ├── tensorflow-cpu
    │   │   │   └── simple
    │   │   │       └── tensorflow
    │   │   │           ├── tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl
    │   │   │           ├── tensorflow-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl
    │   │   │           ├── tensorflow-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl
    │   │   │           ├── tensorflow-1.9.0-cp27-cp27mu-manylinux1_x86_64.whl
    │   │   │           └── tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl
    │   │   └── tensorflow-gpu
    │   │       └── simple
    │   │           └── tensorflow
    │   │               └── tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl
```

**Comment by goern** [comment]
Isn't the GPU whacked build just called 'TensorFlow' from 2.0 on? @sub-mod

**Comment by sub-mod** [comment]
yes @goern

**Comment by fridex** [comment]
> ```
> └── os
> ...
>     ├── fedora
>     │   ├── 26
>     │   │   └── tensorflow-cpu
>     │   │       └── simple
>     │   │           └── tensorflow
>     │   │               └── tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl
>     │   ├── 27
>     │   │   ├── tensorflow-cpu
>     │   │   │   └── simple
>     │   │   │       └── tensorflow
>     │   │   │           ├── tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl
>     │   │   │           ├── tensorflow-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl
>     │   │   │           ├── tensorflow-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl
>     │   │   │           ├── tensorflow-1.9.0-cp27-cp27mu-manylinux1_x86_64.whl
>     │   │   │           └── tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl
>     │   │   └── tensorflow-gpu
>     │   │       └── simple
>     │   │           └── tensorflow
>     │   │               └── tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl
> ```

Is this last one tensorflow-gpu or just tensorflow?

As there will be three variants - `tensorflow-cpu`, `tensorflow-gpu` and `tensorflow`, can we provide them all under `os/<os-name>/<os-version>/<build-configuration>/simple/<package-name>/`? My point is to have one structure and have capability to easily manage updates.

**Comment by fridex** [comment]
Related: https://github.com/thoth-station/init-job/issues/212

**Comment by harshad16** [comment]
> Isn't the GPU whacked build just called 'TensorFlow' from 2.0 on? 

@goern  I have integrated these changes in the new commit. 

> Is this last one tensorflow-gpu or just tensorflow?

@fridex 
The last one had a tag gpu, so it showed up in gpu builds. Anyway the tensorflow-gpu would only show up for manylinux2010 tf 2.0 .

> As there will be three variants - `tensorflow-cpu`, `tensorflow-gpu` and `tensorflow`, can we provide them all under `os/<os-name>/<os-version>/<build-configuration>/simple/<package-name>/`? My point is to have one structure and have capability to easily manage updates.


@fridex 
there would be three variants for the manylinux build, for the older os builds it would be tensorflow. 
we could have the older structure for the builds in os centric.

**Comment by harshad16** [comment]
After new changes new structure:

```
index
├── manylinux2010
│   ├── tensorflow
│   │   └── simple
│   │       ├── tensorflow
│   │       │   ├── tensorflow-1.12.3-cp27-cp27mu-linux_x86_64.whl
│   │       │   ├── tensorflow-1.12.3-cp36-cp36m-linux_x86_64.whl
│   │       │   ├── tensorflow-1.13.2-cp36-cp36m-linux_x86_64.whl
│   │       │   ├── tensorflow-1.14.1-cp27-cp27mu-linux_x86_64.whl
│   │       │   ├── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
│   │       │   ├── tensorflow-1.15.0rc2-cp36-cp36m-linux_x86_64.whl
│   │       │   └── tensorflow-1.15.0rc2-cp37-cp37m-linux_x86_64.whl
│   │       └── tensorflow-serving-api
│   │           ├── tensorflow_serving_api-1.12.3-py2.py3-none-any.whl
│   │           ├── tensorflow_serving_api-1.13.0-py2.py3-none-any.whl
│   │           └── tensorflow_serving_api-1.14.0-py2.py3-none-any.whl
│   ├── tensorflow-cpu
│   │   └── simple
│   │       └── tensorflow
│   │           ├── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
│   │           ├── tensorflow-2.0.0-cp37-cp37m-linux_x86_64.whl
│   │           ├── tensorflow-2.0.0rc0-cp27-cp27mu-linux_x86_64.whl
│   │           └── tensorflow-2.0.0rc0-cp36-cp36m-linux_x86_64.whl
│   └── tensorflow-gpu
│       └── simple
│           └── tensorflow
│               ├── tensorflow-2.0.0rc2-cp36-cp36m-linux_x86_64.whl
│               ├── tensorflow-gpu-2.0.0-cp36-cp36m-linux_x86_64.whl
│               ├── tensorflow-gpu-2.0.0-cp37-cp37m-linux_x86_64.whl
│               └── tensorflow-gpu-2.0.0rc2-cp36-cp36m-linux_x86_64.whl
└── os
    ├── centos
    │   └── 7
    │       └── tensorflow
    │           └── simple
    │               ├── tensorflow
    │               │   ├── tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl
    │               │   ├── tensorflow-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl
    │               │   ├── tensorflow-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl
    │               │   ├── tensorflow-1.12.0-cp36-cp36m-manylinux1_x86_64.whl
    │               │   ├── tensorflow-1.12.2-cp36-cp36m-manylinux1_x86_64.whl
    │               │   ├── tensorflow-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl
    │               │   ├── tensorflow-1.13.1-cp36-cp36m-manylinux1_x86_64.whl
    │               │   ├── tensorflow-1.9.0-cp27-cp27mu-manylinux1_x86_64.whl
    │               │   └── tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl
    │               └── tensorflow-serving-api
    │                   ├── tensorflow_serving_api-1.12.0-py2.py3-none-any.whl
    │                   ├── tensorflow_serving_api-1.13.0-py2.py3-none-any.whl
    │                   └── tensorflow_serving_api-1.14.0-py2.py3-none-any.whl
    ├── fedora
    │   ├── 26
    │   │   └── tensorflow
    │   │       └── simple
    │   │           └── tensorflow
    │   │               └── tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl
    │   ├── 27
    │   │   └── tensorflow
    │   │       └── simple
    │   │           └── tensorflow
    │   │               ├── tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl
    │   │               ├── tensorflow-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl
    │   │               ├── tensorflow-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl
    │   │               ├── tensorflow-1.9.0-cp27-cp27mu-manylinux1_x86_64.whl
    │   │               └── tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl
    │   ├── 28
    │   │   ├── tensorflow
    │   │   │   └── simple
    │   │   │       ├── tensorflow
    │   │   │       │   ├── tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl
    │   │   │       │   ├── tensorflow-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl
    │   │   │       │   ├── tensorflow-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl
    │   │   │       │   ├── tensorflow-1.12.0-cp36-cp36m-manylinux1_x86_64.whl
    │   │   │       │   ├── tensorflow-1.13.1-cp36-cp36m-manylinux1_x86_64.whl
    │   │   │       │   ├── tensorflow-1.9.0-cp27-cp27mu-manylinux1_x86_64.whl
    │   │   │       │   ├── tensorflow-1.9.0-cp35-cp35m-manylinux1_x86_64.whl
    │   │   │       │   └── tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl
    │   │   │       └── tensorflow-serving-api
    │   │   │           ├── tensorflow_serving_api-1.12.0-py2.py3-none-any.whl
    │   │   │           ├── tensorflow_serving_api-1.13.0-py2.py3-none-any.whl
    │   │   │           └── tensorflow_serving_api-1.14.0-py2.py3-none-any.whl
    │   │   └── tensorflow-cpu
    │   │       └── simple
    │   │           └── tensorflow
    │   │               └── tensorflow-2.0.0a0-cp36-cp36m-manylinux1_x86_64.whl
```

**Comment by goern** [comment]
what about 

1. we have tensorflow builds that are
1.1. CPU only - for <2.0 and >= 2.1
1.2. GPU/CPU mixed - for =2.0
1.3. GPU only - for <2.0 and >= 2.1

2. we have TF builds that are
2.1. compliant with manylinux2010
2.2. distribution-specific
2.3. compliant with manylinux2010 but with higher than google's optimization compile-time flags flags

For 1.1 && 2.1 we point pipenv to `https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/tensorflow-cpu`, 
for 1.2. && 2.3. to `https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010-avx512/tensorflow-gpu`
etc..

```
.
└── index
    ├── manylinux2010
    │   ├── tensorflow-cpu
    │   │   └── simple
    │   │       ├── tensorflow
    │   │       │   ├── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
    │   │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
    │   │       └── tensorflow-cpu
    │   │           └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
    │   └── tensorflow-gpu
    │       ├── tensorflow
    │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
    │       ├── tensorflow-cpu
    │       │   └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
    │       └── tensorflow-gpu
    │           └── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
    ├── manylinux2010-avx512
    │   ├── tensorflow-cpu
    │   │   └── simple
    │   │       ├── tensorflow
    │   │       │   ├── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
    │   │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
    │   │       └── tensorflow-cpu
    │   │           └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
    │   └── tensorflow-gpu
    │       ├── tensorflow
    │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
    │       ├── tensorflow-cpu
    │       │   └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
    │       └── tensorflow-gpu
    │           └── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
    └── os
        └── fedora
            └── 30
                ├── tensorflow-cpu
                │   └── simple
                │       ├── tensorflow
                │       │   ├── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
                │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
                │       └── tensorflow-cpu
                │           └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
                └── tensorflow-gpu
                    ├── tensorflow
                    │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
                    ├── tensorflow-cpu
                    │   └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
                    └── tensorflow-gpu
                        └── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl

```

**Comment by fridex** [comment]
> what about
> 
> 1. we have tensorflow builds that are
>    1.1. CPU only - for <2.0 and >= 2.1
>    1.2. GPU/CPU mixed - for =2.0
>    1.3. GPU only - for <2.0 and >= 2.1
> 2. we have TF builds that are
>    2.1. compliant with manylinux2010
>    2.2. distribution-specific
>    2.3. compliant with manylinux2010 but with higher than google's optimization compile-time flags flags
> 
> For 1.1 && 2.1 we point pipenv to `https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/tensorflow-cpu`,
> for 1.2. && 2.3. to `https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010-avx512/tensorflow-gpu`
> etc..
> 
> ```
> .
> └── index
>     ├── manylinux2010
>     │   ├── tensorflow-cpu
>     │   │   └── simple
>     │   │       ├── tensorflow
>     │   │       │   ├── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
>     │   │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
>     │   │       └── tensorflow-cpu
>     │   │           └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl

This will not work with pip/Pipenv integration, directories have to be named based on package names - `tensorflow-cpu` directory holds a package named `tensorflow` (pip/Pipenv will expect package named `tensorflow-cpu`).

>     │   └── tensorflow-gpu

There is missing `simple/` to be consistent and compliant with Python's simple repository API.

>     │       ├── tensorflow
>     │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
>     │       ├── tensorflow-cpu
>     │       │   └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
>     │       └── tensorflow-gpu
>     │           └── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
>     ├── manylinux2010-avx512

Can we have build time-specific configuration as a subdirectory to be consistent with os-specific releases? This would become `manylinux2010/avx512`.

>     │   ├── tensorflow-cpu
>     │   │   └── simple
>     │   │       ├── tensorflow
>     │   │       │   ├── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
>     │   │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
>     │   │       └── tensorflow-cpu
>     │   │           └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
>     │   └── tensorflow-gpu
>     │       ├── tensorflow
>     │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
>     │       ├── tensorflow-cpu
>     │       │   └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
>     │       └── tensorflow-gpu
>     │           └── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
>     └── os
>         └── fedora
>             └── 30
>                 ├── tensorflow-cpu
>                 │   └── simple
>                 │       ├── tensorflow
>                 │       │   ├── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
>                 │       │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
>                 │       └── tensorflow-cpu
>                 │           └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
>                 └── tensorflow-gpu
>                     ├── tensorflow
>                     │   └── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
>                     ├── tensorflow-cpu
>                     │   └── tensorflow-2.1.0dev0-cp36-cp36m-linux_x86_64.whl
>                     └── tensorflow-gpu
>                         └── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
> ```

The package naming inconsistencies is affected on multiple parts of the index - if package is named `tensorflow`, the directory which it should go to should be named `tensorflow`. The same for `tensorflow-gpu` and `tensorflow-cpu`.

What is not clear to me - why do we need to distinguish `tensorflow-cpu`, `tensorflow-gpu` and `tensorflow`? Why we cannot just stick with the schema which adds build-time information to package URL and then follow simple API?

* manylinux2010 compliant builds:
  * `manylinux2010/<build-configuration>/simple/<package-name>/*.whl`
* OS specific releases:
  * `<os-name>/<os-version><build-configuration>/simple/<package-name>/*.whl`

Where package name for TensorFlow project is `tensorflow`, `tensorflow-cpu` and `tensorflow-gpu`:

For TensorFlow releases <2.0:

* `tensorflow-gpu` with GPU support
* `tensorflow` for CPU version of TensorFlow

For TensorFlow releases >=2.0:

* `tensorflow-gpu` for GPU specific builds (if still applicable)
* `tensorflow` for CPU+GPU releases (basically what Google provides)
* `tensorflow-cpu` for "lightweight" releases targetting CPU

With this schema we are basically replicating what PyPI offers, except for the prefix before `simple/` (which is value-add of our builds):

* OS specific releases: `<os-name>/<os-version><build-configuration>/simple`
* manylinux2010 compliant builds `manylinux2010/<build-configuration>/simple`

**Comment by harshad16** [comment]
After discussing, I have made the following changes. 
- OS-specific builds are not displayed on the index, as they container vulnerabilities.
- the build-configuration like avx flag is used to display the index structure.
manylinux2010 compliant builds: `manylinux2010/<build-configuration(AVX)>/simple`

the following structure is formulated:
```
index
└── manylinux2010
    └── AVX2
        └── simple
            ├── tensorflow
            │   ├── tensorflow-1.12.3-cp27-cp27mu-linux_x86_64.whl
            │   ├── tensorflow-1.12.3-cp36-cp36m-linux_x86_64.whl
            │   ├── tensorflow-1.13.2-cp36-cp36m-linux_x86_64.whl
            │   ├── tensorflow-1.14.1-cp27-cp27mu-linux_x86_64.whl
            │   ├── tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl
            │   ├── tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
            │   ├── tensorflow-2.0.0-cp37-cp37m-linux_x86_64.whl
            │   ├── tensorflow-2.0.0rc0-cp27-cp27mu-linux_x86_64.whl
            │   └── tensorflow-2.0.0rc0-cp36-cp36m-linux_x86_64.whl
            ├── tensorflow-cpu
            │   ├── tensorflow_cpu-1.15.0rc2-cp36-cp36m-linux_x86_64.whl
            │   └── tensorflow_cpu-1.15.0rc2-cp37-cp37m-linux_x86_64.whl
            ├── tensorflow-gpu
            │   ├── tensorflow_gpu-2.0.0-cp36-cp36m-linux_x86_64.whl
            │   ├── tensorflow_gpu-2.0.0-cp37-cp37m-linux_x86_64.whl
            │   └── tensorflow_gpu-2.0.0rc2-cp36-cp36m-linux_x86_64.whl
            └── tensorflow-serving-api
                ├── tensorflow_serving_api-1.12.3-py2.py3-none-any.whl
                ├── tensorflow_serving_api-1.13.0-py2.py3-none-any.whl
                └── tensorflow_serving_api-1.14.0-py2.py3-none-any.whl
```

**Comment by goern** [comment]
Please have a look at the readme describing the ibex too

**Comment by harshad16** [comment]
> Please have a look at the readme describing the ibex too

@goern what is ibex?

**Comment by goern** [comment]
index... sorry.. #failByAutocorrection
this file: https://tensorflow.pypi.thoth-station.ninja/index.html

**Review by goern — APPROVED** [review]

**Pull request merged**
